# Import external modules
import random
from faker import Faker

from app.server.modules.clock.Clock import Clock

class SecurityAlert:
    """
    Represents a security alert generated by an organization's security systems
    """

    def __init__(self, time: float, alert_type: str, severity: str, description: str,
                 hostname: str = "", username: str = "", technique_id: str = ""):
        self.time = Clock.from_timestamp_to_string(time)
        self.alert_type = alert_type
        self.severity = severity  #high, med, low
        self.description = description
        # Structured, joinable fields (default "" so existing producers are unaffected).
        # hostname / username let an alert be correlated to host & identity telemetry;
        # technique_id is the MITRE ATT&CK id so it ties to the registry and challenges.
        self.hostname = hostname or ""
        self.username = username or ""
        self.technique_id = technique_id or ""

    def stringify(self):
        """
        Returns the security alert as a dictionary in JSON format.
        NOTE: key order must match get_kql_repr() — ingestion maps positionally (CSV).
        """
        return {
            "timestamp": self.time,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "description": self.description,
            "hostname": self.hostname,
            "username": self.username,
            "technique_id": self.technique_id
        }

    @staticmethod
    def get_kql_repr():
        """
        Returns the KQL representation of the SecurityAlert class.
        Column order must match stringify() (positional CSV ingestion). New columns are
        appended after the original four so existing column positions are preserved.
        """
        return (
            "SecurityAlerts",    # table name
            {                   # type dict
                "timestamp": "datetime",
                "alert_type": "string",
                "severity": "string",
                "description": "string",
                "hostname": "string",
                "username": "string",
                "technique_id": "string"
            }
        )
